/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_forwolk_test_JNIHelloWorld */

#ifndef _Included_ru_forwolk_test_JNIHelloWorld
#define _Included_ru_forwolk_test_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_forwolk_test_JNIHelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_forwolk_test_JNIHelloWorld_printHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     ru_forwolk_test_JNIHelloWorld
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_forwolk_test_JNIHelloWorld_multiply
        (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
